import type { TestProtocol } from "./types";

/**
 * V0.1 protocol catalogue.
 *
 * The catalogue is versioned reference data, not user data: it lives in code and
 * is mirrored into the `test_protocols` table by the migration + seed so the
 * database stays self-describing. Bump `protocolVersion` whenever a change makes
 * older results non-comparable — the UI warns instead of comparing blindly.
 */
export const TEST_PROTOCOLS: TestProtocol[] = [
  {
    id: "b1a1f6d0-0000-4000-8000-000000000001",
    slug: "juggling",
    name: "Juggling",
    description:
      "Maximum number of consecutive touches without the ball hitting the ground.",
    category: "TECHNICAL",
    positionRelevance: {
      GK: "LOW",
      CB: "LOW",
      RB: "LOW",
      LB: "LOW",
      RWB: "LOW",
      LWB: "LOW",
      DM: "MEDIUM",
      CM: "MEDIUM",
      AM: "MEDIUM",
      RW: "MEDIUM",
      LW: "MEDIUM",
      ST: "MEDIUM",
    },
    instructions: [
      "Flat surface, properly inflated match ball.",
      "Start with the ball in hand, drop it and begin.",
      "Any body part except the hands and arms is allowed.",
      "The attempt ends when the ball touches the ground.",
      "3 attempts, 60 s rest between attempts. Best attempt is kept.",
    ],
    equipment: ["1 ball"],
    attempts: 3,
    restSeconds: 60,
    unit: "touches",
    measurementType: "OBJECTIVE",
    improvementDirection: "HIGHER_IS_BETTER",
    defaultReliability: "HIGH",
    protocolVersion: 1,
    active: true,
    aggregation: "BEST",
    attemptLabel: "Touches",
  },
  {
    id: "b1a1f6d0-0000-4000-8000-000000000002",
    slug: "slalom-ball-control",
    name: "Slalom Ball Control",
    description:
      "Standard 6-cone slalom with the ball, timed. Touched or skipped cones add a time penalty.",
    category: "TECHNICAL",
    positionRelevance: {
      GK: "NONE",
      CB: "LOW",
      RB: "MEDIUM",
      LB: "MEDIUM",
      RWB: "HIGH",
      LWB: "HIGH",
      DM: "MEDIUM",
      CM: "MEDIUM",
      AM: "HIGH",
      RW: "HIGH",
      LW: "HIGH",
      ST: "MEDIUM",
    },
    instructions: [
      "6 cones in a straight line, 2 m apart (10 m from first to last cone).",
      "Start line 2 m before the first cone, finish line 2 m after the last cone: 14 m total.",
      "Start on your own signal, ball at the start line, timer starts on first touch.",
      "Slalom through every cone with the ball, then dribble across the finish line.",
      "Timer stops when the ball crosses the finish line.",
      "Penalty: +0.5 s per cone touched or skipped (configurable below).",
      "3 attempts, 90 s rest. Best corrected time is kept.",
    ],
    equipment: ["6 cones", "1 ball", "Phone video or stopwatch"],
    attempts: 3,
    restSeconds: 90,
    unit: "s",
    measurementType: "OBJECTIVE",
    improvementDirection: "LOWER_IS_BETTER",
    defaultReliability: "MEDIUM",
    protocolVersion: 1,
    active: true,
    aggregation: "BEST",
    attemptLabel: "Raw time (s)",
    extraFields: [
      {
        key: "cone_faults",
        label: "Cones touched or skipped (best attempt)",
        type: "number",
        min: 0,
        max: 12,
        step: 1,
        help: "Each fault adds the penalty below to the recorded time.",
      },
      {
        key: "penalty_seconds",
        label: "Penalty per fault",
        type: "number",
        unit: "s",
        min: 0,
        max: 5,
        step: 0.1,
        help: "Protocol default is 0.5 s. Keep it identical across sessions.",
      },
    ],
    notes:
      "The recorded value is the best raw time plus cone_faults x penalty_seconds.",
  },
  {
    id: "b1a1f6d0-0000-4000-8000-000000000003",
    slug: "passing-accuracy-strong-foot",
    name: "Passing Accuracy — Strong Foot",
    description: "20 passes with the strong foot onto a standardised target.",
    category: "TECHNICAL",
    positionRelevance: {
      GK: "MEDIUM",
      CB: "HIGH",
      RB: "HIGH",
      LB: "HIGH",
      RWB: "HIGH",
      LWB: "HIGH",
      DM: "HIGH",
      CM: "HIGH",
      AM: "HIGH",
      RW: "MEDIUM",
      LW: "MEDIUM",
      ST: "MEDIUM",
    },
    instructions: [
      "Target: 1 m wide gate made of 2 cones, placed 15 m away.",
      "Ball starts stationary, one preparation touch allowed.",
      "20 passes with the strong foot, ground passes only.",
      "A pass counts if the ball goes through the gate without touching a cone.",
      "Record the number of successful passes out of 20.",
    ],
    equipment: ["4 cones", "1 ball", "Tape measure or 15 counted steps"],
    attempts: 1,
    restSeconds: 0,
    unit: "/20",
    measurementType: "OBJECTIVE",
    improvementDirection: "HIGHER_IS_BETTER",
    defaultReliability: "HIGH",
    protocolVersion: 1,
    active: true,
    aggregation: "SINGLE",
    attemptLabel: "Successful passes (out of 20)",
    maxValue: 20,
  },
  {
    id: "b1a1f6d0-0000-4000-8000-000000000004",
    slug: "passing-accuracy-weak-foot",
    name: "Passing Accuracy — Weak Foot",
    description: "Same protocol as the strong foot test, played with the weak foot.",
    category: "TECHNICAL",
    positionRelevance: {
      GK: "MEDIUM",
      CB: "MEDIUM",
      RB: "MEDIUM",
      LB: "MEDIUM",
      RWB: "MEDIUM",
      LWB: "MEDIUM",
      DM: "HIGH",
      CM: "HIGH",
      AM: "MEDIUM",
      RW: "MEDIUM",
      LW: "MEDIUM",
      ST: "MEDIUM",
    },
    instructions: [
      "Identical setup to the strong foot test: 1 m gate at 15 m.",
      "20 passes with the weak foot only, ground passes.",
      "A pass counts if the ball goes through the gate without touching a cone.",
      "Record the number of successful passes out of 20.",
    ],
    equipment: ["4 cones", "1 ball"],
    attempts: 1,
    restSeconds: 0,
    unit: "/20",
    measurementType: "OBJECTIVE",
    improvementDirection: "HIGHER_IS_BETTER",
    defaultReliability: "HIGH",
    protocolVersion: 1,
    active: true,
    aggregation: "SINGLE",
    attemptLabel: "Successful passes (out of 20)",
    maxValue: 20,
  },
  {
    id: "b1a1f6d0-0000-4000-8000-000000000005",
    slug: "crossing-accuracy",
    name: "Crossing Accuracy",
    description:
      "12 crosses scored 0/1/2 across three target zones. Designed for full-backs and wingers.",
    category: "POSITIONAL",
    positionRelevance: {
      GK: "NONE",
      CB: "NONE",
      RB: "HIGH",
      LB: "HIGH",
      RWB: "HIGH",
      LWB: "HIGH",
      DM: "LOW",
      CM: "MEDIUM",
      AM: "MEDIUM",
      RW: "HIGH",
      LW: "HIGH",
      ST: "LOW",
    },
    instructions: [
      "Crossing spot: on the flank, level with the edge of the box.",
      "Mark three target zones in the box: near post, central, far post (each ~4 m wide).",
      "12 crosses: 4 near post, 4 central, 4 far post, in that order.",
      "Score each cross: 0 = missed, 1 = acceptable zone, 2 = precise target.",
      "Ball delivered from a stationary or rolling start, same for every session.",
      "Maximum score: 24. Zone scores are stored separately.",
    ],
    equipment: ["12 balls (or a retriever)", "6 cones to mark the zones"],
    attempts: 1,
    restSeconds: 0,
    unit: "/24",
    measurementType: "SEMI_OBJECTIVE",
    improvementDirection: "HIGHER_IS_BETTER",
    defaultReliability: "MEDIUM",
    protocolVersion: 1,
    active: true,
    aggregation: "SUM",
    attemptLabel: "Zone score",
    extraFields: [
      { key: "near_post", label: "Near post (4 crosses)", type: "number", min: 0, max: 8, step: 1 },
      { key: "central", label: "Central zone (4 crosses)", type: "number", min: 0, max: 8, step: 1 },
      { key: "far_post", label: "Far post (4 crosses)", type: "number", min: 0, max: 8, step: 1 },
    ],
    maxValue: 24,
  },
  {
    id: "b1a1f6d0-0000-4000-8000-000000000006",
    slug: "finishing-accuracy",
    name: "Finishing Accuracy",
    description: "20 strikes from the edge of the box. Goals, shots on target and misses are stored.",
    category: "TECHNICAL",
    positionRelevance: {
      GK: "NONE",
      CB: "LOW",
      RB: "LOW",
      LB: "LOW",
      RWB: "LOW",
      LWB: "LOW",
      DM: "LOW",
      CM: "MEDIUM",
      AM: "HIGH",
      RW: "HIGH",
      LW: "HIGH",
      ST: "HIGH",
    },
    instructions: [
      "20 strikes from the edge of the box, one preparation touch allowed.",
      "Same sequence every session: 10 strong foot, 10 weak foot.",
      "Goal = ball inside the goal frame. On target = on frame but saved or hitting the woodwork line.",
      "Miss = off frame.",
      "goals + shots_on_target + misses must equal 20.",
    ],
    equipment: ["20 balls (or a retriever)", "1 goal"],
    attempts: 1,
    restSeconds: 0,
    unit: "goals /20",
    measurementType: "OBJECTIVE",
    improvementDirection: "HIGHER_IS_BETTER",
    defaultReliability: "HIGH",
    protocolVersion: 1,
    active: true,
    aggregation: "SINGLE",
    attemptLabel: "Goals",
    extraFields: [
      { key: "shots_on_target", label: "On target (not scored)", type: "number", min: 0, max: 20, step: 1 },
      { key: "misses", label: "Missed", type: "number", min: 0, max: 20, step: 1 },
    ],
    maxValue: 20,
  },
  {
    id: "b1a1f6d0-0000-4000-8000-000000000007",
    slug: "sprint-10m",
    name: "Sprint 10 m",
    description: "Standing-start 10 m sprint, timed manually from video or stopwatch.",
    category: "PHYSICAL",
    positionRelevance: {
      GK: "MEDIUM",
      CB: "MEDIUM",
      RB: "HIGH",
      LB: "HIGH",
      RWB: "HIGH",
      LWB: "HIGH",
      DM: "MEDIUM",
      CM: "MEDIUM",
      AM: "HIGH",
      RW: "HIGH",
      LW: "HIGH",
      ST: "HIGH",
    },
    instructions: [
      "Mark start and finish with cones, 10 m apart.",
      "Standing start, front foot on the line, no rocking step.",
      "Film side-on at the highest frame rate your phone allows, or use a stopwatch.",
      "3 attempts, 3 min rest. Best and mean times are both kept.",
      "Always warm up the same way — cold sprints are not comparable.",
    ],
    equipment: ["2 cones", "Phone video or stopwatch"],
    attempts: 3,
    restSeconds: 180,
    unit: "s",
    measurementType: "OBJECTIVE",
    improvementDirection: "LOWER_IS_BETTER",
    defaultReliability: "MEDIUM",
    protocolVersion: 1,
    active: true,
    aggregation: "BEST",
    attemptLabel: "Time (s)",
  },
  {
    id: "b1a1f6d0-0000-4000-8000-000000000008",
    slug: "sprint-20m",
    name: "Sprint 20 m",
    description: "Standing-start 20 m sprint, timed manually from video or stopwatch.",
    category: "PHYSICAL",
    positionRelevance: {
      GK: "MEDIUM",
      CB: "MEDIUM",
      RB: "HIGH",
      LB: "HIGH",
      RWB: "HIGH",
      LWB: "HIGH",
      DM: "MEDIUM",
      CM: "MEDIUM",
      AM: "HIGH",
      RW: "HIGH",
      LW: "HIGH",
      ST: "HIGH",
    },
    instructions: [
      "Mark start and finish with cones, 20 m apart.",
      "Standing start, front foot on the line, no rocking step.",
      "Film side-on at the highest frame rate your phone allows, or use a stopwatch.",
      "3 attempts, 3 min rest. Best and mean times are both kept.",
    ],
    equipment: ["2 cones", "Phone video or stopwatch"],
    attempts: 3,
    restSeconds: 180,
    unit: "s",
    measurementType: "OBJECTIVE",
    improvementDirection: "LOWER_IS_BETTER",
    defaultReliability: "MEDIUM",
    protocolVersion: 1,
    active: true,
    aggregation: "BEST",
    attemptLabel: "Time (s)",
  },
  {
    id: "b1a1f6d0-0000-4000-8000-000000000009",
    slug: "sprint-30m",
    name: "Sprint 30 m",
    description: "Standing-start 30 m sprint, timed manually from video or stopwatch.",
    category: "PHYSICAL",
    positionRelevance: {
      GK: "LOW",
      CB: "MEDIUM",
      RB: "HIGH",
      LB: "HIGH",
      RWB: "HIGH",
      LWB: "HIGH",
      DM: "MEDIUM",
      CM: "MEDIUM",
      AM: "MEDIUM",
      RW: "HIGH",
      LW: "HIGH",
      ST: "HIGH",
    },
    instructions: [
      "Mark start and finish with cones, 30 m apart.",
      "Standing start, front foot on the line, no rocking step.",
      "Film side-on at the highest frame rate your phone allows, or use a stopwatch.",
      "3 attempts, 4 min rest. Best and mean times are both kept.",
    ],
    equipment: ["2 cones", "Phone video or stopwatch"],
    attempts: 3,
    restSeconds: 240,
    unit: "s",
    measurementType: "OBJECTIVE",
    improvementDirection: "LOWER_IS_BETTER",
    defaultReliability: "MEDIUM",
    protocolVersion: 1,
    active: true,
    aggregation: "BEST",
    attemptLabel: "Time (s)",
  },
  {
    id: "b1a1f6d0-0000-4000-8000-000000000010",
    slug: "timed-run",
    name: "Timed Run",
    description:
      "Generic endurance protocol: run a standardised distance as fast as possible. Pace is derived.",
    category: "PHYSICAL",
    positionRelevance: {
      GK: "LOW",
      CB: "MEDIUM",
      RB: "HIGH",
      LB: "HIGH",
      RWB: "HIGH",
      LWB: "HIGH",
      DM: "HIGH",
      CM: "HIGH",
      AM: "MEDIUM",
      RW: "MEDIUM",
      LW: "MEDIUM",
      ST: "MEDIUM",
    },
    instructions: [
      "Pick a standardised distance and keep it identical across sessions.",
      "Flat course, same route every time (track preferred).",
      "Same warm-up, ideally similar weather and time of day.",
      "Record total time. Pace per kilometre is computed automatically.",
      "Results are only comparable within the same distance.",
    ],
    equipment: ["Measured course or track", "Stopwatch or phone"],
    attempts: 1,
    restSeconds: 0,
    unit: "s",
    measurementType: "OBJECTIVE",
    improvementDirection: "LOWER_IS_BETTER",
    defaultReliability: "MEDIUM",
    protocolVersion: 1,
    active: true,
    aggregation: "SINGLE",
    attemptLabel: "Total time (s)",
    variantField: "distance_m",
    extraFields: [
      {
        key: "distance_m",
        label: "Distance",
        type: "select",
        options: [
          { value: "1000", label: "1000 m" },
          { value: "1500", label: "1500 m" },
          { value: "2000", label: "2000 m" },
          { value: "3000", label: "3000 m" },
          { value: "5000", label: "5000 m" },
        ],
        help: "Only runs over the same distance are compared with each other.",
      },
    ],
    notes:
      "Yo-Yo IR1, beep test and repeated-sprint protocols will plug into this same category later.",
  },
];

export const PROTOCOLS_BY_SLUG: Record<string, TestProtocol> = Object.fromEntries(
  TEST_PROTOCOLS.map((p) => [p.slug, p]),
);

export function getProtocol(slug: string): TestProtocol | undefined {
  return PROTOCOLS_BY_SLUG[slug];
}

export function activeProtocols(): TestProtocol[] {
  return TEST_PROTOCOLS.filter((p) => p.active);
}
